### ISSUE TITLE
Use k2cli to manage charts from the config file

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken#122]
In a config file, you have a list of charts:
```
      charts:
        - name: heapster
          registry: quay.io
          chart: samsung_cnct/heapster
          version: '0.1.0-0'
          namespace: kube-system
        - name: nginx-ingress
          registry: quay.io
          chart: samsung_cnct/nginx-ingress
          version: '0.2.1-0'
          namespace: kube-auth
          values:
            ingressController:
              class: nginx
```
etc...

It would be nice to be able to manage these charts with k2cli, for example say I updated the version to 0.2.0-0. I should be able to make that change with:
```
k2cli charts --config /mycluster.yaml upgrade nginx-ingress
```
or say I add a new list item to the config and want to install it
```
        - name: dex
          registry: quay.io
          chart: samsung_cnct/dex
          version: '0.1.0-0'
          namespace: kube-auth
          values:
            service:
              type: ClusterIP
            ingress:
              enabled: true
              hosts:
                - auth.domain.dom
            dex:
              Issuer: https://auth.domain.dom/
              RedirectUri: https://auth.domain.dom/callback
            connector:
              GitHub:
                Name: Github
                # Add an org level oauth ID and Secret
                ClientID: badd0gf00d
                ClientSecret: 2698c86753095dc8edb7aaaf00d80cab600dad5f
```

```
k2cli charts --config /mycluster.yaml install dex
```
