### ISSUE TITLE
docs out of date (still referencing old config style)

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken#170]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

Documentation (main README at least)  is out of date on chunks of this file. Several places are still referencing the old config style, example in the section about Environment Variable Expansion: 
```
deployment:
  cluster: production-cluster
  keypair:
    -
      name: key
      publickeyFile:
      privatekeyFile:
      providerConfig:
        username:
        serviceAccount: "serviceaccount@project.iam.gserviceaccount.com"
        serviceAccountKeyFile: "$MY_SERVICE_ACCOUNT_KEYFILE"
```
