### ISSUE TITLE
Kraken 1.8 cluster-wide failure after uptime of ~2 days

### ISSUE THREAD

**Issue by notjames** [samsung-cnct/kraken#203]
Using the following minimal config (see below) advised by the documentation [here](https://github.com/samsung-cnct/kraken#how-to-create-a-small-research-or-development-cluster) to set up a r&d cluster:

we are experiencing cluster-wide node failure after an uptime of just a couple of days.

**Kraken version** (use `kraken version`):
1.2.2-stable

**Environment**:

Please be sure not to submit any confidential information (e.g. ssh keys, provider secrets, etc.) as issues are publicly accessible.

- **Environment variables** (e.g. `env | grep 'KRAKEN_`):
- **Configuration files (`~/.kraken/config.yaml` or the file passed to `kraken --config`) **:

No other changes made to config after `kraken generate` except what documentation recommends for node counts and adding `deployment.clusters.name`:

```
# This is the core of the new configuration.

deployment:
  clusters:
    - name: some-name
      network: 10.32.0.0/12
      dns: 10.32.0.2
      domain: cluster.local
      providerConfig: *defaultAws
      nodePools:
        - name: etcd
          # 5 nodes recommended for production/high availability clusters. This
          # configuration is required to tolerate a single node failure during
          # node upgrades.
          count: 1
          etcdConfigs: [*defaultEtcd, *defaultEtcdEvents]
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsEtcdNode
          keyPair: *defaultKeyPair
        - name: master
          count: 1
          apiServerConfig: *defaultApiServer
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsMasterNode
          keyPair: *defaultKeyPair
        - name: clusterNodes
          count: 1
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsClusterNode
          keyPair: *defaultKeyPair
        - name: specialNodes
          count: 4
          # m4.large
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsSpecialNode
          keyPair: *defaultKeyPair
      fabricConfig: *kubeVersionedFabric
      kubeAuth: *rbacKubeAuth
      helmConfig: *defaultHelm
      dnsConfig: *defaultDns
      # customApiDns:
      helmOverride:
  readiness:
    type: exact
    value: 0
    wait: 600
```

**What happened**:
Still conducting tests. This has happened 4/4 times in the last week and it requires downing and re-upping the cluster to clear the state:

```
$ k2g all --all-namespaces
NAMESPACE         NAME                                                    READY     STATUS     RESTARTS   AGE       IP             NODE
default           po/busybox                                              1/1       Unknown    0          1d        10.128.4.2     ip-10-0-34-75.ec2.internal
default           po/vault-6f4c655fdf-6hzdx                               0/1       Pending    0          13h       <none>         <none>
default           po/vault-6f4c655fdf-k8m2g                               1/1       Unknown    0          1d        10.128.0.4     ip-10-0-159-66.ec2.internal
default           po/vault-6f4c655fdf-lhc7r                               0/1       Pending    0          13h       <none>         <none>
default           po/vault-6f4c655fdf-sq7ph                               1/1       Unknown    0          1d        10.128.3.3     ip-10-0-127-48.ec2.internal
default           po/vault-6f4c655fdf-v2glc                               1/1       Unknown    0          1d        10.128.4.5     ip-10-0-34-75.ec2.internal
default           po/vault-6f4c655fdf-x89tx                               0/1       Pending    0          13h       <none>         <none>
default           po/vault-etcd-vault-etcd-0                              1/1       Unknown    0          1d        10.128.2.2     ip-10-0-114-127.ec2.internal
default           po/vault-etcd-vault-etcd-1                              1/1       Unknown    0          1d        10.128.0.3     ip-10-0-159-66.ec2.internal
default           po/vault-etcd-vault-etcd-2                              1/1       Unknown    0          1d        10.128.4.3     ip-10-0-34-75.ec2.internal
kube-networking   po/canal-6zqp7                                          3/3       NodeLost   0          1d        10.0.114.127   ip-10-0-114-127.ec2.internal
kube-networking   po/canal-7lsgr                                          3/3       Running    0          1d        10.0.52.70     ip-10-0-52-70.ec2.internal
kube-networking   po/canal-8978k                                          3/3       NodeLost   0          1d        10.0.127.48    ip-10-0-127-48.ec2.internal
kube-networking   po/canal-lwwsr                                          3/3       NodeLost   0          1d        10.0.34.75     ip-10-0-34-75.ec2.internal
kube-networking   po/canal-vbg89                                          3/3       NodeLost   0          1d        10.0.157.253   ip-10-0-157-253.ec2.internal
kube-networking   po/canal-vqd55                                          3/3       NodeLost   0          1d        10.0.159.66    ip-10-0-159-66.ec2.internal
kube-system       po/heapster-standalone-5888c67d89-wkmtq                 2/2       Unknown    0          1d        10.128.1.2     ip-10-0-157-253.ec2.internal
kube-system       po/heapster-standalone-5888c67d89-x9wbd                 0/2       Pending    0          13h       <none>         <none>
kube-system       po/kube-apiserver-ip-10-0-52-70.ec2.internal            1/1       Running    0          1d        10.0.52.70     ip-10-0-52-70.ec2.internal
kube-system       po/kube-controller-manager-ip-10-0-52-70.ec2.internal   1/1       Running    0          1d        10.0.52.70     ip-10-0-52-70.ec2.internal
kube-system       po/kube-dns-f79c6789b-tvgjb                             0/3       Pending    0          13h       <none>         <none>
kube-system       po/kube-dns-f79c6789b-wbrt5                             3/3       Unknown    0          1d        10.128.3.2     ip-10-0-127-48.ec2.internal
kube-system       po/kube-proxy-ip-10-0-114-127.ec2.internal              0/1       Pending    0          13h       <none>         ip-10-0-114-127.ec2.internal
kube-system       po/kube-proxy-ip-10-0-127-48.ec2.internal               0/1       Pending    0          13h       <none>         ip-10-0-127-48.ec2.internal
kube-system       po/kube-proxy-ip-10-0-157-253.ec2.internal              0/1       Pending    0          13h       <none>         ip-10-0-157-253.ec2.internal
kube-system       po/kube-proxy-ip-10-0-159-66.ec2.internal               0/1       Pending    0          13h       <none>         ip-10-0-159-66.ec2.internal
kube-system       po/kube-proxy-ip-10-0-34-75.ec2.internal                0/1       Pending    0          13h       <none>         ip-10-0-34-75.ec2.internal
kube-system       po/kube-proxy-ip-10-0-52-70.ec2.internal                1/1       Running    0          1d        10.0.52.70     ip-10-0-52-70.ec2.internal
kube-system       po/kube-scheduler-ip-10-0-52-70.ec2.internal            1/1       Running    0          1d        10.0.52.70     ip-10-0-52-70.ec2.internal
kube-system       po/tiller-deploy-cffb976df-jfrxx                        0/1       Pending    0          13h       <none>         <none>
kube-system       po/tiller-deploy-cffb976df-sjw9f                        1/1       Unknown    0          1d        10.128.0.2     ip-10-0-159-66.ec2.internal
```

**What you expected to happen**:
A healthy running cluster

**How to reproduce it** (as minimally and precisely as possible):
fork/clone the following repos: [chart-vault-etcd](/chart-vault-etcd), [cyklops-config-vault](/cyklops-config-vault), [chart-vault](/chart-vault)
To reproduce, one could perform the following steps:

1. set up environment with above-mentioned config
2. `kraken cluster up`
3. helm install etcd (see bullets)
  * $ cd /path/to/chart-vault-etcd/vault-etcd
  * $ helm --debug install -f values.yaml --name vault-etcd .
4. helm install vault (see bullets)
  * $ cd /path/to/chart-vault/vault-chart
  * $ helm --debug install -f ~/path/to/cyklops-config-vault/vault-svc-values.yaml --name vault .
5. wait for a day or so

**Anything else we need to know**:
captured cluster state for the 3 of the 4 last times this happened:

[cluster-20171026.txt](https://github.com/samsung-cnct/kraken/files/1428208/cluster-20171026.txt)
[cluster-20171028.txt](https://github.com/samsung-cnct/kraken/files/1428209/cluster-20171028.txt)
[cluster-20171030.txt](https://github.com/samsung-cnct/kraken/files/1428210/cluster-20171030.txt)
[k8s-issue-get-alls.txt](https://github.com/samsung-cnct/kraken/files/1428281/k8s-issue-get-alls.txt)

Finally, I've spun up a new cluster using the steps above. One thing I haven't done is some log grokking from the nodes themselves, so when the cluster fails then I'll update the ticket with new relevant info. I've also spun up just a plain vanilla cluster with the config above (no vault or etcd) to see if vault/etcd are culprit. I'll update this ticket if and when I get any information there.
